
{
    'name': 'Maz Alumec Ajo',
    'version': '1.1',
    'category': 'Sales',
    'summary': 'Alumec Ajo.',
    'description': """This module created to handle aluminum job order for alumec.""",
    'author': 'MAZ',
    'company': 'MAZ',
    'maintainer': 'MAZ',
    'website': "https://www.maz.com",
    'depends': ['base', 'mail', 'crm', 'sale_management', 'account', 'stock','purchase','sales_team','sale_stock','mrp'],
    'data': [
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'wizard/product_label_layout_views.xml',
        'wizard/ajo_import_wizard_views.xml',
        'views/product_views.xml',
        'views/purchase_order_views.xml',
        'views/mrp_dimensions_views.xml',
        'views/ajo_window_template_views.xml',
        'views/ajo_order_views.xml',
        'views/ajo_order_window_views.xml',
        'views/cutlist_sum_views.xml',
        'views/purchase_iso_checklist_views.xml',
        'report/product_reports.xml',
        'report/product_template_templates.xml',
        'data/cutlist_stage_data.xml',
        'data/ajo_window_template_technal_fxi_fixed.xml',
        'data/ajo_offcut_sequence.xml',
        #'views/main_menu_color.xml'
    ],
    'external_dependencies': {
        'python': ['openpyxl'],
    },
    'images': ['static/description/alumec.png'],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
